### PR TITLE
Add v8.4.0 manually

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
For some reason the bot isn't working, so I manually pushed for updates. But we should wait for a bit longer and see if the bot is glitched or not.

**Comment by jakirkham** [comment]
cc @conda-forge/bot

**Comment by jakirkham** [comment]
Went ahead and filed issue ( https://github.com/regro/cf-scripts/issues/1345 ) about the missing bot PR. Let's see what others say 🙂

**Comment by leofang** [comment]
Thanks, John! Let's proceed with this PR as it might take some time to investigate. I'll try [CJ's suggestion](https://github.com/conda-forge/cupy-feedstock/issues/62#issuecomment-769947176) in another PR later. My guess is somehow failing to migrate also blocks the bot for regular version updates.

**Pull request merged**
