### PR TITLE
Use run_export in v6

### PR DESCRIPTION
**Pull request by leofang**
Close #18.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender.

**Comment by leofang** [comment]
Should I bump the build number here?

**Comment by jakirkham** [comment]
Yeah that would be good. Then feel free to merge once CI is green.

Thanks again for the work here. 🙂

**Comment by leofang** [comment]
@conda-forge-admin, please rerender.

**Comment by leofang** [comment]
All checks passed. Merging now. Thanks a lot for your help, @jakirkham!!!

**Pull request merged**
