### PR TITLE
Set/unset CUDA_PATH in activate/deactivate

### LINKED ISSUE #46: Add new activation script and/or run dependency?
Continuing the discussion from https://github.com/AnacondaRecipes/cudatoolkit-feedstock/pull/5#issuecomment-603454124 and https://github.com/cupy/cupy/issues/3222#issuecomment-603449808:
1. It'd be much better if `nvcc` can exist in a conda env where CuPy is installed
2. If not, we should set `CUDA_PATH` for CuPy to look up where CUDA is in the conda env.

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Close #46. This makes `python -c 'import cupy; cupy.show_config()'` print the correct `CUDA Root`, and also prepares us for AnacondaRecipes/cudatoolkit-feedstock#5.

rel: cupy/cupy#3222

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please lint

**Comment by leofang** [comment]
@jakirkham @kmaehashi What do you think?

**Comment by jakirkham** [comment]
Sorry for the delay Leo. 😞 Also thanks for working on this. 🙂

From the standpoint of ensuring CuPy loads libraries from `cudatoolkit`, this seems reasonable. Maybe we do this as an interim solution until we figure out how to address issue ( https://github.com/cupy/cupy/issues/3222 )?

That said, I'm wondering if any other libraries are using `CUDA_PATH` or whether it would interact with them. Do you know?

**Comment by leofang** [comment]
> Sorry for the delay Leo. 😞 Also thanks for working on this. 🙂

Don't be! I also wanted a cooldown period to think about alternative solutions, so I didn't ping you. 

> From the standpoint of ensuring CuPy loads libraries from `cudatoolkit`, this seems reasonable. Maybe we do this as an interim solution until we figure out how to address issue ( [cupy/cupy#3222](https://github.com/cupy/cupy/issues/3222) )?

Yeah I wouldn't say this is interim but it *is* one possible solution.  
> That said, I'm wondering if any other libraries are using `CUDA_PATH` or whether it would interact with them. Do you know?

I need your knowledge on the RAPIDS stack. I see that both Numba and PyTorch use `CUDA_HOME`, so at least our choice is safe for them, but I can't speak for certain for other libraries...

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@jakirkham This is ready. PTAL.

**Comment by jakirkham** [comment]
Let's go ahead and merge. Thanks for working on this Leo! 😄

**Comment by jakirkham** [comment]
Should we backport this to `v6`?

**Comment by leofang** [comment]
Thanks, John! I think it's alright. Not really a bug, and v7 has been out for quite some time.

**Pull request merged**
