### PR TITLE
Use global pinning for cudnn

### LINKED ISSUE #21: Remove explicit cuDNN pinning
The explicit pinning (via `run_export`)
https://github.com/conda-forge/cupy-feedstock/blob/eddbda9367c972757552646d1abe8ac8c1662e44/recipe/meta.yaml#L45
can be avoided once the upstream (conda-forge-pinning) is updated.

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #21. ~~***DO NOT MERGE*** until @jakirkham confirms conda-forge/conda-forge-pinning-feedstock#352 is in effect.~~ Another sibling PR will be made for the v6 branch.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Yeah we still need a new version of `conda-forge-pinning` for this to work.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
cudnn 7.6.4 is pinned now

**Comment by leofang** [comment]
@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
Weird...The CIs did not run?
@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
Here we go...

**Comment by jakirkham** [comment]
Thanks @leofang! 😄

**Pull request merged**
