### PR TITLE
Avoid building from sdist

### LINKED ISSUE #98: `cupy.show_config()` errors out
```
$ conda create -n test -c conda-forge -y python=3.8 cupy cudatoolkit=11.0
$ conda activate test
$ python -c "import cupy; cupy.show_config()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leofang/miniforge3/envs/test/lib/python3.8/site-packages/cupy/__init__.py", line 866, in show_config
    _sys.stdout.write(str(_cupyx.get_runtime_info()))
  File "/home/leofang/miniforge3/envs/test/lib/python3.8/site-packages/cupyx/_runtime.py", line 225, in __str__
    props['name'].decode('utf-8')),
AttributeError: 'str' object has no attribute 'decode'
```
For some reason `CUDA_VERSION` was either unset or set to 0 at build time, so this line was picked up:
https://github.com/cupy/cupy/blob/89da620875741bbb167512234ab3a9f81b5ffc10/cupy_backends/cuda/api/runtime.pyx#L293
together with another byte <-> str bug (https://github.com/cupy/cupy/pull/4594) this error happens.

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fix #98.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Another option might be to recythonize generating fresh C/C++ code (assuming I understand the upstream issue correctly, which I may not)

**Comment by leofang** [comment]
> Another option might be to recythonize generating fresh C/C++ code (assuming I understand the upstream issue correctly, which I may not)

Yes you understood it right John, though it'd involve patching `setup.py`/`cupy_setup_build.py` to force cythonizing. Changing the source seems easier (all tests have passed).

**Comment by jakirkham** [comment]
I think there is a way to force cythonization, but yeah it's not always easy.

**Pull request merged**
