### PR TITLE
Added ppc64le support for cuda 11.6

### PR DESCRIPTION
**Pull request by alhad-deshpande**
Added ppc64le build for cuda toolkit version 11.6.
Ran conda smithy rerender and committed changed files.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by leofang — CHANGES_REQUESTED** [review]
Hi @alhad-deshpande May I ask again why we need to use CUDA 11.6 to build? Similar to librmm, here we've also enabled the CUDA Enhanced Compatibility support so using CuPy with `cudatoolkit=11.6` should have no problem.

**Comment by alhad-deshpande** [comment]
> Hi @alhad-deshpande May I ask again why we need to use CUDA 11.6 to build? Similar to librmm, here we've also enabled the CUDA Enhanced Compatibility support so using CuPy with `cudatoolkit=11.6` should have no problem.

Hi @leofang Getting an error that cupy-116 is not available. Hence need to get that.

**Comment by alhad-deshpande** [comment]
> That doesn't make sense. Could you please try
> 
> ```
> conda install -c conda-forge cupy cudatoolkit=11.6
> ```

Ok, will try this. But my goal is to make available CUDF 21.12.00 on conda-forge and it has mentioned that CUDF requires CUDA toolkit >= 11.5 - https://github.com/rapidsai/cudf/blob/v21.12.00/CONTRIBUTING.md#setting-up-your-build-environment

Hence I was building all the required dependencies against CUDA 11.6. Installing with above command will install cupy/librmm against CUDA 11.6 but they are built against 11.2 which should not cause any runtime issues. 

Please let me know your views.

**Comment by leofang** [comment]
@jakirkham can correct me, but CuPy is not a build time dependency of cuDF but a runtime one, and it doesn't matter which CUDA version CuPy was built against, as long as the ABI is compatible (which is guaranteed by the Enhanced Compatibility). You made your life too hard @alhad-deshpande, it's not that complicated 🙂

**Comment by alhad-deshpande** [comment]
> @jakirkham can correct me, but CuPy is not a build time dependency of cuDF but a runtime one, and it doesn't matter which CUDA version CuPy was built against, as long as the ABI is compatible (which is guaranteed by the Enhanced Compatibility). You made your life too hard @alhad-deshpande, it's not that complicated 🙂

@leofang , Understood. Thanks for all your help :)

**Comment by leofang** [comment]
Yup np, if there's any issue that requires a newer CUDA at build time, let's revisit it, otherwise let's let the conda solver to solve for the dependencies and not expand the build matrix.

**Pull request closed without merging**
