### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by Ethyling**
Add aarch64 support

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Ethyling** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@Ethyling Thanks for your PR. As you can see the infrastructure on Conda-Forge is not yet ready for building CUDA packages for aarch64...😅 If you're interested, https://github.com/conda-forge/cudatoolkit-feedstock/ has a few lingering PR waiting for completion. Also, check out https://conda-forge.org/docs/maintainer/knowledge_base.html?#cuda-builds and see what I meant by infrastructure. There are some other missing work.

**Comment by Ethyling** [comment]
@leofang Thank you, I will check all of this!

**Comment by leofang** [comment]
(ps: I updated the link in my reply)

**Pull request closed without merging**
