### PR TITLE
Add v9.0.0b2 manually

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc: @grlee77

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Leo! 😀

**Comment by leofang** [comment]
Hi @jakirkham Question: if the bot is working, would it update the rc branch for us?

**Comment by jakirkham** [comment]
No IIRC we disabled pre releases from the bot. While sometimes useful, there were too many cases where they caused problems. We have occasionally discussed selectively enabling them on some feedstocks via an opt-in mechanism. Though this hasn’t come up in a while

**Comment by leofang** [comment]
Cool, thanks John. Then this PR can be merged.

**Pull request merged**
