### PR TITLE
Patch a CUB bug in v7.1.0

### LINKED ISSUE #31: Pulling 7.1.0
It appears there was a pretty serious bug in CuPy 7.1.0. ( https://github.com/cupy/cupy/issues/2971 ) Would like to pull the packages from conda-forge so that others don't run into this issue. Thoughts?

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #31. The applied patch fixes cupy/cupy#2971.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge/cupy Can anyone test this PR and confirm that the updated package is bug free? I can't run docker on any of the GPU machines that I can access...Thanks!

**Comment by leofang** [comment]
CI passed.

**Comment by jakirkham** [comment]
> Can anyone test this PR and confirm that the updated package is bug free? I can't run docker on any of the GPU machines to which I have access...Thanks!

It should be possible to run the build locally (even on a non-GPU machine) using the `build-locally.py` script. The package will be placed in the `build_artifacts` directory in the feedstock. This file can be used to install the package on a GPU machine for testing.

**Comment by leofang** [comment]
> It should be possible to run the build locally (even on a non-GPU machine) using the `build-locally.py` script. The package will be placed in the `build_artifacts` directory in the feedstock. This file can be used to install the package on a GPU machine for testing.

Good point, thanks! I will build on my laptop and then test on a GPU machine later today.

**Comment by jakirkham** [comment]
Sounds good. Please let me know if you have any issues. Happy to help out 🙂

**Comment by leofang** [comment]
@jakirkham Thanks a lot for the tips! I was able to built and test locally (on different machines). The bug is fixed with your patch. Please feel free to merge.

cc: @shwina

**Comment by jakirkham** [comment]
Thanks so much for your work on this @leofang! 😄

**Pull request merged**
