### PR TITLE
Add v8.5.0 manually

### PR DESCRIPTION
**Pull request by leofang**
~~Blocked by #104.~~

Changes in this PR:
- Bump to v8.5.0
- Add CUDA 11.2
- Change the source back to sdist (i.e. revert #100) as it's fixed upstream (cupy/cupy#4619)
- Add cuDNN v8.1 support for CUDA 10.2+

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Please hold off merging by ~12 hrs. #104 is in and I wanna know if the bot is able to send this update PR or not.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Sounds like this is because the bot ignores git cloned repos ( https://github.com/regro/cf-scripts/issues/1345#issuecomment-787070560 ). So shouldn’t be an issue now that we are switching back to PyPI

**Comment by jakirkham** [comment]
Thanks Leo! 😀

**Pull request merged**
