### PR TITLE
Update to v7.3.0

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

cc: @jakirkham

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Should get #43 addressed.

**Comment by leofang** [comment]
CUDA 9.2 + PY38 connection error. I don't think there's any problem, but for safety let me restart CI...

@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
I guess we managed to get a bot update PR just now ( https://github.com/conda-forge/cupy-feedstock/pull/45 )

**Comment by leofang** [comment]
...did @beckermr fix the bot, or did it just wake up? 🤣

**Comment by leofang** [comment]
Thanks, John. Let's bring the PyPy issue to upstream and proceed as is!

**Pull request merged**
