### PR TITLE
Handle unset CUDA_PATH even when set -u option active

### PR DESCRIPTION
**Pull request by calebmarchent**
Fixes: #68

Test Plan:
  $ set -u
  $ conda activate test_cupy_path
  With fix applied we no longer get CUDA_PATH: unbound variable

### CODE REVIEW

**Review by leofang — CHANGES_REQUESTED** [review]
Thank you for reporting and fixing the issue, @calebmarchent! Just one quick request: I think this qualifies as a bug fix, so could you please bump the build number in the recipe? Otherwise LGTM.

**Comment by jakirkham** [comment]
Yeah we won't get new packages without a build number bump 😉

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Review by leofang — APPROVED** [review]
LGTM! Thanks again.

**Comment by leofang** [comment]
(Looks like the bot doesn't check existing PRs very frequently, so I clicked "rerun" to make the automerge label in effect. Just my little experiment 😁)

**Comment by jakirkham** [comment]
Yeah it doesn't run on PRs that already passed. We are on our own to merge those 😉

**Pull request merged**
