### PR TITLE
Support cuTENSOR

### PR DESCRIPTION
**Pull request by leofang**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge/cupy This PR expands the build matrix to support cuTENSOR. All tests passed, PTAL. 

On CUDA 11.0, it works straightforwardly as the `glibc` version 2.17 used in the CentOS 7 image is new enough. On 10.1/10.2, the CentOS 6 image has glibc 2.12, which cuTENSOR does not support, so in additional to the original builds I also add the combination of glibc 2.17 + CUDA 10.1/10.2, which adds an extra 12 outputs. If this strategy is OK I'll port it to the rc branch (#95).

**Comment by leofang** [comment]
cc: @jakirkham

**Comment by leofang** [comment]
Merge to prepare for the upcoming release.

**Comment by jakirkham** [comment]
Thanks Leo! 😄

**Pull request merged**
